
# application.properties
spring.datasource.url=jdbc:mysql://127.0.0.1:3306/devdb?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=devuser
spring.datasource.password=devpass
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

# Optional (for better dev experience)
spring.sql.init.mode=always


# Show only relevant log level in dev
logging.level.root=INFO
logging.level.org.springframework.boot.autoconfigure=ERROR
logging.level.org.hibernate=ERROR


spring.servlet.multipart.max-file-size=200MB
spring.servlet.multipart.max-request-size=250MB