spring.application.name=LifeCourse Platform
spring.main.banner-mode=off
spring.profiles.active=dev

server.servlet.context-path=/life
app.message.sender=event

springdoc.api-docs.resolve-schema-properties=true
springdoc.api-docs.enabled=true
springdoc.api-docs.cache.disabled=false
springdoc.api-docs.auto-init=true
